ifeq ($(MAKING_MODULES),1)
-include $(TOPDIR)/Rules.make
endif

LINUX24:=2.4
EXTRA_CFLAGS +=-DREVISION_VERSION=\"\ rv$(REVISION)\"

ifneq ($(strip $(findstring $(LINUX24),$(LINUX_VERSION))),$(LINUX24))

obj-m += batgat.o
batgat-objs := gateway.o hash.o

else

modules: batgat.o

batgat.o: gateway24.o hash.o
	$(LD) -r $^ -o $@

endif
